RecettesIngredients/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recettes.urls'), name='home_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recettes/urls.py
from django.urls import path
from . import views


app_name = "home_page"
urlpatterns = [
    path('', views.index, name='index'),
    path('settings/create/', views.create_recipe, name='create_recipe'),
    path('settings/ingredient/', views.add_ingredient, name='add_ingredient'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('ingredients/', views.ingredient_list, name='ingredient_list'),
    path('settings/', views.settings, name='settings'),
    path('ingredients/<int:ingredient_id>/edit_ingredient/', views.edit_ingredient, name='edit_ingredient'),
    path('ingredients/<int:ingredient_id>/delete_ingredient/', views.delete_ingredient, name='delete_ingredient'),
    path('recipes/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipes/<int:recipe_id>/recipe_edit/', views.recipe_edit, name='recipe_edit'),
    path('recipes/<int:recipe_id>/recipe_delete/', views.recipe_delete, name='recipe_delete'),

]

recettes/models.py
from django.db import models
from django.contrib.postgres.fields import *


class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    count = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"


class Recipe(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000, default='')
    recette = models.TextField(max_length=1000, default='')
    ingredients = models.CharField(default='', max_length=1000)
    #ingredients_array = ArrayField(models.CharField(max_length=100), default = list)
    image = models.ImageField(upload_to='uploads/', default='uploads/unknown.png')

    def save(self, *args, **kwargs):
        # convertir la liste d'ingrédients en chaîne de caractères
        self.ingredients = self.ingredients.replace("<QuerySet [<Ingredient: ",'')
        self.ingredients = self.ingredients.replace(">",'')
        self.ingredients = self.ingredients.replace(" <Ingredient: ",'')
        self.ingredients = self.ingredients.replace("]",'')


        '''self.ingredients_array = self.ingredients.split(",")
        print(self.ingredients_array)'''

        super().save(*args, **kwargs)


    def __str__(self):
        return self.name



    '''def save(self, *args, **kwargs):
        # convertir la liste d'ingrédients en chaîne de caractères
        ingredients_list = [ingredient.name for ingredient in self.ingredients.all()]
        self.ingredients = ','.join(ingredients_list)

        super().save(*args, **kwargs)

    def get_ingredients_list(self):
        # convertir la chaîne de caractères en liste
        return self.ingredients.split(',')'''

recettes/forms.py
from django import forms
from .models import Recipe, Ingredient


class RecipeForm(forms.ModelForm):
    name = forms.CharField(max_length=255, required=True)
    description = forms.CharField(widget=forms.Textarea)

    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    def clean_ingredients(self):
        selected_values = self.cleaned_data.get('ingredients')
        if not selected_values:
            raise forms.ValidationError("Veuillez sélectionner au moins un ingrédient.")
        return selected_values


    recette = forms.CharField(widget=forms.Textarea, required=False)

    image = forms.ImageField(required=False)

    class Meta:
        model = Recipe
        fields = ['name', 'description', 'ingredients', 'recette', 'image']

    '''def clean_new_ingredient_name(self):
        name = self.cleaned_data.get('new_ingredient')
        if name and Ingredient.objects.filter(name__iexact=name).exists():
            raise forms.ValidationError('Cet ingrédient existe déjà.')
        return name

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save()
        ingredients = self.cleaned_data.get('ingredients')
        new_ingredient = self.cleaned_data.get('new_ingredient')
        if new_ingredient:
            ingredient, created = Ingredient.objects.get_or_create(name=new_ingredient)
            ingredients.append(ingredient)
        instance.ingredients.set(ingredients)
        return instance'''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ingredients'].required = False


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']

    def clean_name(self):
        name = self.cleaned_data['name']
        if Ingredient.objects.filter(name=name).exists():
            raise forms.ValidationError('Cet ingrédient existe déjà')
        return name

recettes/views.py
from django.db.models import ProtectedError
from django.http import Http404
from django.shortcuts import render
from .models import Recipe
from django.shortcuts import render, redirect
from .forms import RecipeForm, IngredientForm
from .models import Ingredient
from django.views.generic import ListView
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse


class IngredientListView(ListView):
    model = Ingredient
    template_name = 'ingredient_list.html'
    context_object_name = 'ingredients'


def index(request):
    return render(request, 'index.html')


def settings(request):
    # Render the settings.html template and return it as an HTTP response
    return render(request, 'recettes/settings.html')


def recipe_list(request):
    # Récupérer tous les ingrédients de la base de données
    ingredients = Ingredient.objects.all()

    # Récupérer toutes les recettes de la base de données
    recettes = Recipe.objects.all()

    selected_ingredients = request.GET.getlist('ingredient')

    if selected_ingredients:
        # Filtrer les recettes en fonction des ingrédients sélectionnés
        recettes = recettes.filter(ingredients__name__in=selected_ingredients)

    ingredients = ingredients.order_by('name')
    recettes = recettes.order_by('name')

    # Calculer le nombre de recettes où chaque ingrédient apparaît
    for ingredient in ingredients:
        for recipe in recettes:
            if recipe.ingredients.__contains__(str(ingredient)):
                ingredient.count += 1
        print(ingredient.count)

    context = {
        'ingredients': ingredients,
        'recettes': recettes,
        'selected_ingredients': selected_ingredients
    }

    return render(request, 'recettes/recipe_list.html', context)


def ingredient_list(request):
    try:
        ingredient = Ingredient.objects.all()
    except Ingredient.DoesNotExist:
        # If no Restaurants are found, raise an HTTP 404 error
        raise Http404("No restaurants available.")
    return render(request, 'recettes/ingredient_list.html', {'ingredients': ingredient})


def create_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home_page:recipe_list')
    else:
        form = RecipeForm()
    return render(request, 'recettes/create_recipe.html', {'form': form})


def add_ingredient(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'].lower()
            if Ingredient.objects.filter(name=name).exists():
                messages.warning(request, f"L'ingrédient '{name}' existe déjà.")
            else:
                form.save()
            return redirect('home_page:ingredient_list')
    else:
        form = IngredientForm()
    ingredients = Ingredient.objects.all()
    return render(request, 'recettes/add_ingredient.html', {'form': form, 'ingredients': ingredients})


def delete_ingredient(request, ingredient_id):
    ingredient = Ingredient.objects.get(pk=ingredient_id)
    if request.method == 'POST':
        try:
            ingredient.delete()
            return redirect('../../')
        except ProtectedError:
            error_msg = f"L'ingrédient {ingredient.name} est utilisé dans au moins une recette et ne peut pas être supprimé."
            return render(request, 'recettes/error.html', {'error_msg': error_msg})
    return render(request, 'recettes/delete_ingredient.html', {'ingredient': ingredient})


def delete_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    if request.method == 'POST':
        recipe.delete()
        return redirect('home_page:recipe_list')
    return render(request, 'recettes/delete_recipe.html', {'recipe': recipe})


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    return render(request, 'recettes/recipe_detail.html', {'recipe': recipe})


def recipe_edit(request, recipe_id):
    # get the restaurant object from the database using the restaurant_id parameter
    recipe = Recipe.objects.get(pk=recipe_id)

    # check if the request method is POST
    if request.method == 'POST':
        # create a form object and populate it with data from the request
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            # save the updated restaurant object to the database
            form.save()
            # redirect to the updated restaurant's detail page
            return redirect('../../', recipe.id)
    else:
        # create a form object and populate it with the current values from the restaurant object
        form = RecipeForm(instance=recipe)

    # render the update_restaurant template with the form object as context
    return render(request, 'recettes/recipe_edit.html', {'form': form})


def recipe_delete(request, recipe_id):
    # Retrieve the Restaurant object with the given restaurant ID
    recipe = Recipe.objects.get(pk=recipe_id)

    # If the HTTP request method is POST, delete the Restaurant object from the database and redirect to the index
    # view for all restaurants
    if request.method == 'POST':
        recipe.delete()
        return redirect('../../')

    # If the HTTP request method is not POST, render the remove_restaurant.html template with the Restaurant object
    # passed as context
    return render(request, 'recettes/recipe_delete.html', {'recipe': recipe})


def edit_ingredient(request, ingredient_id):
    # Retrieve the Burger object with the given burger ID
    ingredient = Ingredient.objects.get(pk=ingredient_id)

    # If the HTTP request method is POST, update the Burger object with the submitted form data and redirect to the
    # index view for all burgers
    if request.method == 'POST':
        form = IngredientForm(request.POST, instance=ingredient)
        if form.is_valid():
            # Update the existing Burger object in the database with the submitted form data
            form.save()
            # Redirect to the index view for all burgers with the ID of the updated burger as a URL parameter
            return redirect('../../', ingredient.id)
    else:
        # If the HTTP request method is not POST, render the update_burger.html template with the Burger object and
        # form passed as context
        form = IngredientForm(instance=ingredient)

    return render(request, 'recettes/ingredient_edit.html', {'ingredient': ingredient, 'form': form})

recettes/templates/recettes/add_ingredient.html
{% block content %}
  <h1>Ajouter un ingrédient</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Ajouter l'ingrédient</button>
  </form>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
    <a href="javascript:history.go(-1)">Back</a>
{% endblock %}

recettes/templates/recettes/create_recipe.html
{% block content %}
  <h2>Add Recipe</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
      <!--<button id="add-new-ingredient" type="button">Ajouter ingrédient</button>-->
      <br>
      <br>
    <button type="submit">Add Recipe</button>

  </form>
    <a href="../">Back</a>
{% endblock %}

<script>
    const addNewIngredientBtn = document.querySelector('#add-new-ingredient');
const newIngredientInput = document.querySelector('#id_new_ingredient');
const ingredientList = document.querySelector('#id_ingredients');

addNewIngredientBtn.addEventListener('click', () => {
    const newIngredientName = newIngredientInput.value.trim();
        console.log('New ingredient name:', newIngredientName); // Ajout d'un console.log pour débuguer

    if (newIngredientName !== '') {
        // Vérifier si l'ingrédient existe déjà dans la base de données
        fetch(`/ingredients/check/${newIngredientName}`)
            .then(response => response.json())
            .then(data => {
                if (data.exists) {
                    // Si l'ingrédient existe déjà, ajouter simplement l'option à la liste
                    const newIngredientOption = new Option(newIngredientName, data.id, true, true);
                    ingredientList.append(newIngredientOption);
                } else {
                    // Si l'ingrédient n'existe pas, l'ajouter à la base de données
                    fetch('/ingredients/add/', {
                        method: 'POST',
                        body: JSON.stringify({name: newIngredientName}),
                        headers: {'Content-Type': 'application/json'}
                    })
                    .then(response => response.json())
                    .then(data => {
                        // Ajouter l'option à la liste avec l'ID nouvellement créé
                        const newIngredientOption = new Option(newIngredientName, data.id, true, true);
                        ingredientList.append(newIngredientOption);
                    });
                }
                // Réinitialiser le champ d'ajout d'ingrédient
                newIngredientInput.value = '';
            });
    }
});

</script>

recettes/templates/recettes/delete_ingredient.html
{% block content %}
  <h1>Supprimer l'ingrédient "{{ ingredient.name }}"</h1>
  <p>Êtes-vous sûr de vouloir supprimer l'ingrédient "{{ ingredient.name }}"?</p>
  <form action="" method="POST">
    {% csrf_token %}
    <button type="submit">Supprimer</button>
    <a href="../../">Annuler</a>
  </form>
{% endblock %}

recettes/templates/recettes/delete_recipe.html
{% block content %}
  <h1>Supprimer la recette "{{ recipe.title }}"</h1>
  <p>Êtes-vous sûr de vouloir supprimer la recette "{{ recipe.title }}"?</p>
  <form action="{% url 'recettes:delete_recipe' recipe.pk %}" method="POST">
    {% csrf_token %}
    <button type="submit">Supprimer</button>
    <a href="{% url 'recettes:recipe_list' %}">Annuler</a>
  </form>
{% endblock %}

recettes/templates/recettes/ingredient_edit.html
<h1>Modifier ingrédient</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
 </form>

<a href="../../" class="back-btn">Back</a>

recettes/templates/recettes/ingredient_list.html
{% block content %}
  <h1>Tous les ingrédients</h1>
    {% if not ingredients %}
       {{ "Pas encore d'ingrédients" }}
    {% endif %}
  <ul>
    {% for ingr in ingredients %}
      <li>
        <h2>{{ ingr.name }}

            <a href="{{ ingr.id }}/delete_ingredient/" >Supprimer l'ingrédient</a>
            <a href="{{ ingr.id }}/edit_ingredient/" >Modifier l'ingrédient</a>
        </h2>
      </li>
    {% endfor %}
  </ul>
    <a href="../settings/ingredient/">Ajouter un ingrédient</a>
    <br>
    <br>
    <a href="../">Home</a>
{% endblock %}

recettes/templates/recettes/recipe_delete.html
<h1>Supprimer recette</h1>

<p>Es-tu sûr de supprimer : {{ recipe.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Send">
  <a href="../../" >No</a>
</form>

recettes/templates/recettes/recipe_detail.html
<!DOCTYPE html>
<html>
<head>
  <title>{{ recipe.name }}</title>
  <style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      background-color: #f2f2f2;
    }

    .recipe-card {
        width: 600px; /* Largeur ajustée */
      padding: 20px;
      background-color: #fff;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
      border-radius: 10px;
      text-align: center;
    }

    .recipe-card h1 {
      font-size: 24px;
    }

    .recipe-card p {
      margin-bottom: 20px;
    }

    .recipe-card h2 {
      font-size: 18px;
    }

    .recipe-card ul {
      list-style-type: none;
      padding: 0;
    }

    .recipe-card img {
      width: 200px;
      height: 200px;
      margin-top: 20px;
      border-radius: 50%;
    }

    .recipe-card a {
      display: inline-block;
      margin-top: 20px;
      text-decoration: none;
      color: #333;
      font-weight: bold;
      padding: 10px 20px;
      border: 1px solid #333;
      border-radius: 4px;
      transition: background-color 0.3s ease;
    }

    .recipe-card a:hover {
      background-color: #333;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="recipe-card">
    <h1>{{ recipe.name }}</h1>
    <p>{{ recipe.description }}</p>



    <h2>Ingrédients</h2>
    <ul id="ingredientList"></ul>

  <script>
      var ingredients = "{{ recipe.ingredients }}";
      var ingredientList = ingredients.split(",");

      for (var i = 0; i < ingredientList.length; i++) {
          document.getElementById("ingredientList").innerHTML += "<li>" + "- "+ ingredientList[i] + "</li>";
      }
    </script>

    <h2>Recette</h2>
    <ol>
      {{ recipe.recette }}
    </ol>

    {% if recipe.image == "uploads/unknown.png" %}
      <img src="../../media/uploads/unknown.png" alt="{{ recipe.name }}">
    {% else %}
      <img src="../../media/{{ recipe.image }}" alt="{{ recipe.name }}" width="200" height="200">
    {% endif %}

    <br>
    <br>
    <a href="../">Retour</a>
    <a href="recipe_edit/">Modifier la recette</a>
  </div>
</body>
</html>

recettes/templates/recettes/recipe_edit.html
<h1>Modifier Recette</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
 </form>

<a href="../../" class="back-btn">Back</a>
<a href="../recipe_delete">Supprimer</a>

recettes/templates/recettes/recipe_list.html
<!DOCTYPE html>
<html>
<a href="../">Retour</a>
<head>
  <title>Liste de recettes</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
    }

    h1, h2 {
      margin-bottom: 20px;
    }

    #ingredients {
      margin-bottom: 40px;
    }

    #ingredients label {
      display: inline-block;
      margin-right: 10px;
      margin-bottom: 10px;
    }

    #recettes {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 20px;
    }

    .recette {
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      text-align: center;
    }

    .recette img {
      max-width: 100%;
      height: 150px;
      margin-bottom: 10px;
    }

    .recette a {
      color: #333;
      text-decoration: none;
    }

    .recette a:hover {
      text-decoration: underline;
    }

    .ingredient-count {
      color: gray;
      font-style: italic;
    }
  </style>
</head>
<body>
  <h1>Liste de recettes</h1>

  <h2>Ingrédients disponibles</h2>
  {% if not ingredients %}
      {{ "Pas encore d'ingrédients" }}
  {% endif %}
  <div id="ingredients">
    {% for ingredient in ingredients %}
    <label>
        <input type="checkbox" name="ingredient" value="{{ ingredient }}">{{ ingredient }}
        <span class="ingredient-count">({{ ingredient.count }})</span>
    </label>
    {% endfor %}
  </div>

    <!--<h2>Barre de recherche</h2>
    <input type="text" id="search-input" placeholder="Rechercher..." onkeyup="searchRecipes()">-->



  <h2>Recettes</h2>
  {% if not recettes %}
      {{ "Pas encore de recettes" }}
  {% endif %}
  <div id="recettes">
    {% for recette in recettes %}
    <div class="recette" data-ingredients="{{ recette.ingredients }}">
        {% if recette.image == "uploads/unknown.png" %}
            <img src="../../media/uploads/unknown.png" alt="{{ recette.name }}" width="150px" height="100">
        {% else %}
      <a href="{{ recette.id }}/"><img src="../../media/{{ recette.image }}" alt="{{ recette.name }}" width="150px" height="200"></a>
        {% endif %}
    <br>
    <a href="{{ recette.id }}/">{{ recette.name }}</a>

    </div>
    {% endfor %}
  </div>

  <script>
    console.log("f")
    // Sélectionner les cases à cocher des ingrédients
    const checkboxes = document.querySelectorAll('input[name="ingredient"]');

    // Ajouter un écouteur d'événement pour chaque case à cocher
    checkboxes.forEach(function(checkbox) {
      checkbox.addEventListener('change', function() {
        // Récupérer les ingrédients sélectionnés
        const selectedIngredients = Array.from(document.querySelectorAll('input[name="ingredient"]:checked')).map(function(checkbox) {
          return checkbox.value;
        });

        // Cacher toutes les recettes
        const recettes = document.querySelectorAll('.recette');
        recettes.forEach(function(recette) {
          recette.style.display = 'none';
        });

        // Afficher les recettes qui contiennent les ingrédients sélectionnés
        if (selectedIngredients.length === 0) {
          recettes.forEach(function(recette) {
            recette.style.display = 'block';
          });
        } else {
          recettes.forEach(function(recette) {
            const ingredientsString = recette.getAttribute('data-ingredients');
            const recipeIngredients = ingredientsString.split(',');

            // Vérifier si tous les ingrédients sélectionnés sont présents dans la recette
            const hasAllIngredients = selectedIngredients.every(function(ingredient) {
              return recipeIngredients.includes(ingredient);
            });

            if (hasAllIngredients) {
              recette.style.display = 'block';
            } else {
              recette.style.display = 'none';
            }
          });
        }
      });
    });
    // Fonction de recherche des recettes
  function searchRecipes() {
    // Récupérer la valeur saisie dans la barre de recherche
    const searchValue = document.getElementById('search-input').value.toLowerCase();

    // Récupérer toutes les recettes
    const recettes = document.querySelectorAll('.recette');

    if(searchValue==''){
        recettes.forEach(function(recette) {
            recette.style.display = 'block';
          });
    }
    else{
        // Parcourir les recettes et afficher/cacher en fonction des mots-clés de recherche
      console.log("oui" + searchValue)
    recettes.forEach(function(recette) {
        console.log({{ recette.name }})
      const recetteName = "{{ recette.name }}";
    console.log("ez")
        console.log(recetteName)
      if (recetteName.includes(searchValue) && searchValue!='') {
        recette.style.display = 'block';
      } else {
        recette.style.display = 'none';
      }
    });
    }

  }
  </script>
</body>
<br>
<a href="../">Retour</a>
</html>


recettes/templates/recettes/settings.html
<!DOCTYPE html>
<html>
  <head>
    <title>Settings</title>
  </head>
  <body>
    <h1 style="text-align:center;">Settings</h1>
    <p style="font-size:20px;">Pour créer les recettes</p>
    <div style="display:flex; justify-content: center; margin-top:20px;">
      <a href="create/" style="padding: 10px 20px; background-color: #ff8c00; color: white; border-radius: 5px; margin-right: 20px;">Créer une recette</a>
        <a href="ingredient/" style="padding: 10px 20px; background-color: #ff8c00; color: white; border-radius: 5px; margin-right: 20px;">Ajouter un ingrédient</a>
    </div>
    <div style="text-align:center; margin-top:30px;">
      <a href="../" style="font-size:16px;">Retour à l'accueil</a>
    </div>
  </body>
</html>